module.exports = {
    simsmastatus:-5,
    savedtopstockliststatus: '',
    savedGetMemcachedData: '',
    simulationlog: '',
    simulationlogchunks: [],
    simulonlyonestockcount: 'empty',
    cache: {},
    blackList: [],
    personstocklist: [],
    successpersonstocklist: [],
    
    accounttickerlist : [],
    toptickerlist : [],
    persontickerlist: [],
    breakouttickerlist: [],
    serverfetchtickerlist: [],
    clientfetchtickerlist: [],
    
    excelvalues:'',
    sheets:null,
    sheetList:null,

    // Simulation
    rtickers:[],
    rtickersfast:[],
    simstate:'',
    simticker:'',
    singlesimfirstclose:null,
    singlesimlastclose:null,
    simsingleplus:0,
    simsingleminus:0,
    accounttickerlist:null,//allstockcapitalvalue
    simtableSet:null,
    assetBuyGate:{
        yesterdayUp:false,
        yesterdayDate:'',
        yesterdayChangePer:0,
        todayStartCapital:0,
        todayCashDate:'',
        todayStartCanUseCash:0,
        todaySellCash:0,
        previousSellCash:0,
        todayOldCashUsed:0,
    },
    assetBuyGateYesterdayUp:false,
    assetBuyGateYesterdayDate:'',
    assetBuyGateYesterdayChangePer:0,
    assetBuyGateTodayStartCapital:0,
    assetBuyGateTodayCashDate:'',
    assetBuyGateTodayStartCanUseCash:0,
    assetBuyGateTodaySellCash:0,
    assetBuyGatePreviousSellCash:0,
    assetBuyGateTodayOldCashUsed:0,

    // DEBUGING CHEAT
    pausefetch:false,
    everytimefetch:false,
  };
